# Application configuration
base.url=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login

# default browser (chrome|firefox|edge)
default.browser=chrome

# environment profile (qa|dev|uat|prod)
environment=qa
profile=default

# execution settings
implicit.wait.seconds=10
explicit.wait.seconds=15
headless=false
max.retries=1
